spring.application.name=springauthservice

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_auth
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
api.security.token.secret=joseph-senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true